name: Manual Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g., v0.16-cannary-1, v0.16-cannary-2)'
        required: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Necessary to fetch all history for tags

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get Latest Tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Generate Release Notes
        run: |
          echo 'Release Notes:' > RELEASE_NOTES.md
          git log ${LATEST_TAG}..HEAD --pretty=format:"- [%h](https://github.com/${{ github.repository }}/commit/%H) %s" >> RELEASE_NOTES.md
          echo "RELEASE_NOTES=$(cat RELEASE_NOTES.md)" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag ${{ github.event.inputs.release_tag }}
          git push origin ${{ github.event.inputs.release_tag }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: RELEASE_NOTES.md
          prerelease: true

