name: Manual Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g., v0.16-cannary-1)'
        required: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for tags and branches

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate Release Notes
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Release Notes since $LATEST_TAG" > RELEASE_NOTES.md
          git log ${LATEST_TAG}..HEAD --pretty=format:"- [%h](https://github.com/${{ github.repository }}/commit/%H) %s" >> RELEASE_NOTES.md
          RELEASE_NOTES=$(cat RELEASE_NOTES.md)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag ${{ github.event.inputs.release_tag }}
          git push origin ${{ github.event.inputs.release_tag }}

      - name: Create GitHub Release
        run: |
          gh release create ${{ github.event.inputs.release_tag }} \
            --repo ${{ github.repository }} \
            --title "${{ github.event.inputs.release_tag }}" \
            --notes-file RELEASE_NOTES.md \
            --draft false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


