name: Manual Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g., v0.16-cannary-1)'
        required: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Necessary to fetch all history for tags

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate Release Notes
        id: generate_notes
        run: |
          echo '## What Changed' > RELEASE_NOTES.md
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s by [%an]() in [%h](https://github.com/${{ github.repository }}/commit/%H)" >> RELEASE_NOTES.md
          RELEASE_NOTES=" $(<RELEASE_NOTES.md)"
          RELEASE_NOTES_TRUNCATED=$(echo "$RELEASE_NOTES" | head -c 100000)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES_TRUNCATED" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag ${{ github.event.inputs.release_tag }}
          git push origin ${{ github.event.inputs.release_tag }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.release_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ env. RELEASE_NOTES }}
          prerelease: true
          generateReleaseNotes: true





